version: '2'
services:
    mysql:
        build: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_USER=mjhazbri
            - MYSQL_PASSWORD=mjhazbri
            - MYSQL_DATABASE=mjhazbri
            
    wildfly:
        build: wildfly
        ports:
            - "8080:8080"
            - "9990:9990"
        environment:
            - MYSQL_HOST=mysql:3306
            - MYSQL_USER=mjhazbri
            - MYSQL_PASSWORD=mjhazbri
            - MYSQL_DATABASE=mjhazbri
        depends_on: 
            - mysql